<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="$(BuildingBlocksPackageId)"/>
    <PackageReference Include="JetBrains.Annotations"/>
    <PackageReference Include="Grpc.Net.Client"/>
    <PackageReference Include="Google.Protobuf"/>
    <PackageReference Include="Grpc.Tools"/>
    <PackageReference Include="OpenTelemetry.Api"/>
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\grpc_feevider.proto" GrpcServices="Both"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SharedKernel\ThunderPropagator.Feeviders.SharedKernel\ThunderPropagator.Feeviders.SharedKernel.csproj" />
  </ItemGroup>

</Project>
