<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <TargetFramework>net10.0</TargetFramework>
        <TargetFrameworks />
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Bogus"/>
        <PackageReference Include="JetBrains.Annotations"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="MQTTnet.Server"/>
        <PackageReference Include="NJsonSchema"/>
        <PackageReference Include="NSubstitute"/>
        <PackageReference Include="xunit"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
        <PackageReference Include="coverlet.collector">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Feeviders\InboxOutbox\ThunderPropagator.Feeders.Inbox\ThunderPropagator.Feeders.Inbox.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\RabbitMQ\ThunderPropagator.Feeders.RabbitMQ\ThunderPropagator.Feeders.RabbitMQ.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\WebApi\ThunderPropagator.Feeders.WebApi\ThunderPropagator.Feeders.WebApi.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\WebApi\ThunderPropagator.Providers.DotNet.WebApi\ThunderPropagator.Providers.DotNet.WebApi.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\TcpSocket\ThunderPropagator.Feeders.TcpSocket\ThunderPropagator.Feeders.TcpSocket.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\TcpSocket\ThunderPropagator.Providers.DotNet.TcpSocket\ThunderPropagator.Providers.DotNet.TcpSocket.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\UdpClient\ThunderPropagator.Feeders.UdpClient\ThunderPropagator.Feeders.UdpClient.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\UdpClient\ThunderPropagator.Providers.DotNet.UdpClient\ThunderPropagator.Providers.DotNet.UdpClient.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\UdpClient\ThunderPropagator.Feeviders.UdpClient.SharedKernel\ThunderPropagator.Feeviders.UdpClient.SharedKernel.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\Mqtt\ThunderPropagator.Feeders.Mqtt\ThunderPropagator.Feeders.Mqtt.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\Mqtt\ThunderPropagator.Providers.DotNet.Mqtt\ThunderPropagator.Providers.DotNet.Mqtt.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\NATS\ThunderPropagator.Feeders.NATS\ThunderPropagator.Feeders.NATS.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\NATS\ThunderPropagator.Providers.DotNet.NATS\ThunderPropagator.Providers.DotNet.NATS.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\NATS\ThunderPropagator.Feeviders.NATS.SharedKernel\ThunderPropagator.Feeviders.NATS.SharedKernel.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\Kafka\ThunderPropagator.Feeders.Kafka\ThunderPropagator.Feeders.Kafka.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\Kafka\ThunderPropagator.Providers.DotNet.Kafka\ThunderPropagator.Providers.DotNet.Kafka.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\ActiveMQ\ThunderPropagator.Feeders.ActiveMQ\ThunderPropagator.Feeders.ActiveMQ.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\ActiveMQ\ThunderPropagator.Providers.DotNet.ActiveMQ\ThunderPropagator.Providers.DotNet.ActiveMQ.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\Pulsar\ThunderPropagator.Feeders.Pulsar\ThunderPropagator.Feeders.Pulsar.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\Pulsar\ThunderPropagator.Providers.DotNet.Pulsar\ThunderPropagator.Providers.DotNet.Pulsar.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\RabbitMQ\ThunderPropagator.Providers.DotNet.RabbitMQ\ThunderPropagator.Providers.DotNet.RabbitMQ.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\RedisPubSub\ThunderPropagator.Feeders.RedisPubSub\ThunderPropagator.Feeders.RedisPubSub.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\RedisPubSub\ThunderPropagator.Providers.DotNet.RedisPubSub\ThunderPropagator.Providers.DotNet.RedisPubSub.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\WebSocket\ThunderPropagator.Feeders.WebSocket\ThunderPropagator.Feeders.WebSocket.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\WebSocket\ThunderPropagator.Providers.DotNet.WebSocket\ThunderPropagator.Providers.DotNet.WebSocket.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\AwsSqs\ThunderPropagator.Feeders.AwsSqs\ThunderPropagator.Feeders.AwsSqs.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\AwsSqs\ThunderPropagator.Providers.DotNet.AwsSqs\ThunderPropagator.Providers.DotNet.AwsSqs.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\AwsSqs\ThunderPropagator.Feeviders.AwsSqs.SharedKernel\ThunderPropagator.Feeviders.AwsSqs.SharedKernel.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\AzureServiceBus\ThunderPropagator.Feeders.AzureServiceBus\ThunderPropagator.Feeders.AzureServiceBus.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\AzureServiceBus\ThunderPropagator.Providers.DotNet.AzureServiceBus\ThunderPropagator.Providers.DotNet.AzureServiceBus.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\AzureServiceBus\ThunderPropagator.Feeviders.AzureServiceBus.SharedKernel\ThunderPropagator.Feeviders.AzureServiceBus.SharedKernel.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\GcpPubSub\ThunderPropagator.Feeders.GcpPubSub\ThunderPropagator.Feeders.GcpPubSub.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\GcpPubSub\ThunderPropagator.Providers.DotNet.GcpPubSub\ThunderPropagator.Providers.DotNet.GcpPubSub.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\GcpPubSub\ThunderPropagator.Feeviders.GcpPubSub.SharedKernel\ThunderPropagator.Feeviders.GcpPubSub.SharedKernel.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\Grpc\ThunderPropagator.Feeders.Grpc\ThunderPropagator.Feeders.Grpc.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\Grpc\ThunderPropagator.Providers.DotNet.Grpc\ThunderPropagator.Providers.DotNet.Grpc.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\Grpc\ThunderPropagator.Feeviders.Grpc.SharedKernel\ThunderPropagator.Feeviders.Grpc.SharedKernel.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\ZeroMQ\ThunderPropagator.Feeders.ZeroMQ\ThunderPropagator.Feeders.ZeroMQ.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\ZeroMQ\ThunderPropagator.Providers.DotNet.ZeroMQ\ThunderPropagator.Providers.DotNet.ZeroMQ.csproj" />
        <ProjectReference Include="..\..\..\Feeviders\ZeroMQ\ThunderPropagator.Feeviders.ZeroMQ.SharedKernel\ThunderPropagator.Feeviders.ZeroMQ.SharedKernel.csproj" />
    </ItemGroup>

</Project>
