<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Configurations>Debug;Release;Cluster</Configurations>
        <Platforms>AnyCPU;ARM32;ARM64;x86;x64</Platforms>
        <Version>1.0.4.0</Version>
    </PropertyGroup>

    <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Apache.NMS" Version="2.1.0" />
        <PackageReference Include="Apache.NMS.ActiveMQ" Version="2.1.0" />
    </ItemGroup>

</Project>
