<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations"/>
    <ProjectReference Include="..\..\SharedKernel\ThunderPropagator.Feeders.SharedKernel\ThunderPropagator.Feeders.SharedKernel.csproj"/>
    <ProjectReference Include="..\..\SharedKernel\ThunderPropagator.Feeviders.SharedKernel\ThunderPropagator.Feeviders.SharedKernel.csproj"/>
  </ItemGroup>

</Project>
