<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\SharedKernel\RapidStreamer.Feeders.SharedKernel\RapidStreamer.Feeders.SharedKernel.csproj" />
        <ProjectReference Include="..\RapidStreamer.Feeviders.ActiveMQ.SharedKernel\RapidStreamer.Feeviders.ActiveMQ.SharedKernel.csproj" />
    </ItemGroup>

</Project>
