<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" />
        <ProjectReference Include="..\ThunderPropagator.Feeviders.UdpClient.SharedKernel\ThunderPropagator.Feeviders.UdpClient.SharedKernel.csproj"/>
        <ProjectReference Include="..\..\SharedKernel\ThunderPropagator.Feeders.SharedKernel\ThunderPropagator.Feeders.SharedKernel.csproj"/>
    </ItemGroup>

</Project>