using ThunderPropagator.BuildingBlocks.Application.Serializations;

namespace ThunderPropagator.Feeviders.SharedKernel;

public delegate IFormatDeserializer FormatDeserializerInvoker(SerializerType serializerType);
