using ThunderPropagator.BuildingBlocks.Application.Serializations;

namespace ThunderPropagator.Feeviders.SharedKernel;

public delegate IFormatSerializer FormatSerializerInvoker(SerializerType serializerType);
