<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ThunderPropagator.Feeders.Inbox\ThunderPropagator.Feeders.Inbox.csproj" />
    </ItemGroup>

</Project>
