<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" />
        <ProjectReference Include="..\..\SharedKernel\ThunderPropagator.Providers.DotNet.SharedKernel\ThunderPropagator.Providers.DotNet.SharedKernel.csproj"/>
    </ItemGroup>

</Project>