<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EnablePreviewFeatures>true</EnablePreviewFeatures>
        <Platforms>AnyCPU;ARM32;ARM64;x86;x64</Platforms>
        <Configurations>Debug;Release;Cluster</Configurations>
        <Version>1.0.1.0</Version>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="OpenTelemetry.Api" Version="1.9.0"/>
        <PackageReference Include="RapidStreamer" Version="1.0.7"/>
    </ItemGroup>

</Project>
