<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="$(BuildingBlocksPackageId)" />
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Azure.Messaging.ServiceBus" />
    <PackageReference Include="JetBrains.Annotations" />
    <PackageReference Include="OpenTelemetry.Api" />
  </ItemGroup>

</Project>
