<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
        <Configurations>Debug;Release</Configurations>
        <EnablePreviewFeatures>true</EnablePreviewFeatures>
        <Platforms>AnyCPU;x86;x64;ARM64</Platforms>
        <Version>1.0.41.0</Version>
        <LangVersion>latestmajor</LangVersion>
        <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <DebugSymbols>False</DebugSymbols>
        <DebugType>None</DebugType>
        <DefineConstants />
    </PropertyGroup>

    <PropertyGroup Label="nuget">
        <IsPackable>true</IsPackable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Authors>RapidStreamer</Authors>
        <Description>Redefining real time data streaming; effortless, blazingly fast and cloud-native for maximum impact</Description>
        <Copyright>Copyright ©2024 RapidStreamer Corporation</Copyright>
        <PackageProjectUrl>https://www.rapidstreamer.com</PackageProjectUrl>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/KAB-TEAM/RapidStreamer.Feeviders</RepositoryUrl>
        <PackageTags>Real-Time Data Streaming, Blazingly Fast, Cloud-Native, Data Streaming, Effortless Performance, High Impact, Real-Time Processing, Fast Data Pipelines, Cloud Solutions, Streaming Technology</PackageTags>
        <PackageIcon>RapidStreamer.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <AvoidCycleErrorOnSelfReference>true</AvoidCycleErrorOnSelfReference>
    </PropertyGroup>

    <Choose>
        <When Condition="'$(Configuration)'=='Debug'">
            <Choose>
                <When Condition="'$(Platform)'=='ARM64'">
                    <PropertyGroup>
                        <PackageId>$(RootNameSpace).Debug.ARM64</PackageId>
                    </PropertyGroup>
                </When>
                <When Condition="'$(Platform)'=='x86'">
                    <PropertyGroup>
                        <PackageId>$(RootNameSpace).Debug.x86</PackageId>
                    </PropertyGroup>
                </When>
                <When Condition="'$(Platform)'=='x64'">
                    <PropertyGroup>
                        <PackageId>$(RootNameSpace).Debug.x64</PackageId>
                    </PropertyGroup>
                </When>
                <Otherwise>
                    <PropertyGroup>
                        <PackageId>$(RootNameSpace).Debug</PackageId>
                    </PropertyGroup>
                </Otherwise>
            </Choose>
        </When>
        <Otherwise>
            <Choose>
                <When Condition="'$(Platform)'=='ARM64'">
                    <PropertyGroup>
                        <PackageId>$(RootNameSpace).ARM64</PackageId>
                    </PropertyGroup>
                </When>
                <When Condition="'$(Platform)'=='x86'">
                    <PropertyGroup>
                        <PackageId>$(RootNameSpace).x86</PackageId>
                    </PropertyGroup>
                </When>
                <When Condition="'$(Platform)'=='x64'">
                    <PropertyGroup>
                        <PackageId>$(RootNameSpace).x64</PackageId>
                    </PropertyGroup>
                </When>
                <Otherwise>
                    <PropertyGroup>
                        <PackageId>$(RootNameSpace)</PackageId>
                    </PropertyGroup>
                </Otherwise>
            </Choose>
        </Otherwise>
    </Choose>

    <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\..\RapidStreamer.png" Pack="true" Link="RapidStreamer.png" PackagePath="" />
        <None Include="..\..\..\README.md" Pack="true" Link="README.md" PackagePath="" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\SharedKernel\RapidStreamer.Providers.DotNet.SharedKernel\RapidStreamer.Providers.DotNet.SharedKernel.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="StackExchange.Redis" Version="2.8.16" />
    </ItemGroup>

</Project>
