<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\SharedKernel\ThunderPropagator.Providers.DotNet.SharedKernel\ThunderPropagator.Providers.DotNet.SharedKernel.csproj"/>
        <ProjectReference Include="..\ThunderPropagator.Feeviders.NATS.SharedKernel\ThunderPropagator.Feeviders.NATS.SharedKernel.csproj"/>
    </ItemGroup>

</Project>
