<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\SharedKernel\ThunderPropagator.Providers.DotNet.SharedKernel\ThunderPropagator.Providers.DotNet.SharedKernel.csproj" />
    <ProjectReference Include="..\ThunderPropagator.Feeviders.AzureServiceBus.SharedKernel\ThunderPropagator.Feeviders.AzureServiceBus.SharedKernel.csproj" />
  </ItemGroup>

</Project>
