<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="$(BuildingBlocksPackageId)"/>
        <PackageReference Include="JetBrains.Annotations" />
        <PackageReference Include="MQTTnet"/>
        <PackageReference Include="Microsoft.AspNetCore.Connections.Abstractions"/>
    </ItemGroup>

</Project>