<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="$(BuildingBlocksPackageId)"/>
        <PackageReference Include="Apache.NMS"/>
        <PackageReference Include="Apache.NMS.ActiveMQ"/>
        <PackageReference Include="JetBrains.Annotations" />
    </ItemGroup>

</Project>