<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="$(BuildingBlocksPackageId)"/>
        <PackageReference Include="Apache.NMS"/>
        <PackageReference Include="Apache.NMS.ActiveMQ"/>
        <PackageReference Include="JetBrains.Annotations" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\SharedKernel\ThunderPropagator.Feeders.SharedKernel\ThunderPropagator.Feeders.SharedKernel.csproj" />
      <ProjectReference Include="..\..\SharedKernel\ThunderPropagator.Providers.DotNet.SharedKernel\ThunderPropagator.Providers.DotNet.SharedKernel.csproj" />
    </ItemGroup>

</Project>