<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <EnablePreviewFeatures>true</EnablePreviewFeatures>
        <Platforms>AnyCPU;ARM64;x86;x64</Platforms>
        <TargetFrameworks />
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="NetArchTest.Rules" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>



    <ItemGroup>
        <ProjectReference Include="..\..\Feeviders\AzureServiceBus\ThunderPropagator.Feeders.AzureServiceBus\ThunderPropagator.Feeders.AzureServiceBus.csproj" />
        <ProjectReference Include="..\..\Feeviders\AzureServiceBus\ThunderPropagator.Providers.DotNet.AzureServiceBus\ThunderPropagator.Providers.DotNet.AzureServiceBus.csproj" />
        <ProjectReference Include="..\..\Feeviders\AzureServiceBus\ThunderPropagator.Feeviders.AzureServiceBus.SharedKernel\ThunderPropagator.Feeviders.AzureServiceBus.SharedKernel.csproj" />
        <ProjectReference Include="..\..\Feeviders\GcpPubSub\ThunderPropagator.Feeders.GcpPubSub\ThunderPropagator.Feeders.GcpPubSub.csproj" />
        <ProjectReference Include="..\..\Feeviders\GcpPubSub\ThunderPropagator.Providers.DotNet.GcpPubSub\ThunderPropagator.Providers.DotNet.GcpPubSub.csproj" />
        <ProjectReference Include="..\..\Feeviders\GcpPubSub\ThunderPropagator.Feeviders.GcpPubSub.SharedKernel\ThunderPropagator.Feeviders.GcpPubSub.SharedKernel.csproj" />
        <ProjectReference Include="..\..\Feeviders\Grpc\ThunderPropagator.Feeders.Grpc\ThunderPropagator.Feeders.Grpc.csproj" />
        <ProjectReference Include="..\..\Feeviders\Grpc\ThunderPropagator.Providers.DotNet.Grpc\ThunderPropagator.Providers.DotNet.Grpc.csproj" />
        <ProjectReference Include="..\..\Feeviders\Grpc\ThunderPropagator.Feeviders.Grpc.SharedKernel\ThunderPropagator.Feeviders.Grpc.SharedKernel.csproj" />
    </ItemGroup>

</Project>
