<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Confluent.Kafka"/>
        <PackageReference Include="Confluent.SchemaRegistry"/>
        <PackageReference Include="Confluent.SchemaRegistry.Serdes.Avro"/>
        <PackageReference Include="Confluent.SchemaRegistry.Serdes.Json"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\SharedKernel\ThunderPropagator.Feeders.SharedKernel\ThunderPropagator.Feeders.SharedKernel.csproj"/>
        <ProjectReference Include="..\..\SharedKernel\ThunderPropagator.Providers.DotNet.SharedKernel\ThunderPropagator.Providers.DotNet.SharedKernel.csproj" />
    </ItemGroup>

</Project>
