<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\SharedKernel\RapidStreamer.Providers.DotNet.SharedKernel\RapidStreamer.Providers.DotNet.SharedKernel.csproj"/>
        <ProjectReference Include="..\RapidStreamer.Feeviders.Mqtt.SharedKernel\RapidStreamer.Feeviders.Mqtt.SharedKernel.csproj" />
    </ItemGroup>

</Project>
