<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="$(BuildingBlocksPackageId)"/>
    <PackageReference Include="JetBrains.Annotations"/>
    <PackageReference Include="NATS.Net"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SharedKernel\ThunderPropagator.Feeviders.SharedKernel\ThunderPropagator.Feeviders.SharedKernel.csproj"/>
  </ItemGroup>

</Project>
