<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\SharedKernel\RapidStreamer.Providers.DotNet.SharedKernel\RapidStreamer.Providers.DotNet.SharedKernel.csproj"/>
        <ProjectReference Include="..\RapidStreamer.Feeviders.NATS.SharedKernel\RapidStreamer.Feeviders.NATS.SharedKernel.csproj"/>
    </ItemGroup>

</Project>
