using ThunderPropagator.BuildingBlocks.Application.Serializations;

namespace ThunderPropagator.Feeders.SharedKernel;

public delegate IFormatSerializer FormatSerializerInvoker(SerializerType serializerType);
