<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="$(ThunderPropagatorPackageId)"/>
        <PackageReference Include="JetBrains.Annotations" />
        <PackageReference Include="OpenTelemetry.Api"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\InboxOutbox\ThunderPropagator.Feeders.Inbox\ThunderPropagator.Feeders.Inbox.csproj" />
    </ItemGroup>

</Project>
