<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
        <Configurations>Debug;Release</Configurations>
        <EnablePreviewFeatures>true</EnablePreviewFeatures>
        <Platforms>AnyCPU;x86;x64;ARM64</Platforms>
        <Version>1.0.68.0</Version>
        <LangVersion>latestmajor</LangVersion>
        <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <DebugSymbols>False</DebugSymbols>
        <DebugType>None</DebugType>
        <DefineConstants />
    </PropertyGroup>

    <PropertyGroup Label="nuget">
        <IsPackable>true</IsPackable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Authors>RapidStreamer</Authors>
        <Description>Redefining real time data streaming; effortless, blazingly fast and cloud-native for maximum impact</Description>
        <Copyright>Copyright ©2024 RapidStreamer Corporation</Copyright>
        <PackageProjectUrl>https://www.rapidstreamer.com</PackageProjectUrl>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/KAB-TEAM/RapidStreamer.Feeviders</RepositoryUrl>
        <PackageTags>Real-Time Data Streaming, Blazingly Fast, Cloud-Native, Data Streaming, Effortless Performance, High Impact, Real-Time Processing, Fast Data Pipelines, Cloud Solutions, Streaming Technology</PackageTags>
        <PackageIcon>RapidStreamer.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <AvoidCycleErrorOnSelfReference>true</AvoidCycleErrorOnSelfReference>
        <PackageId Condition="'$(Configuration)' == 'Debug' And '$(Platform)' != 'AnyCPU'">$(RootNameSpace).Debug.$(Platform)</PackageId>
        <PackageId Condition="'$(Configuration)' == 'Debug' And '$(Platform)' == 'AnyCPU'">$(RootNameSpace).Debug</PackageId>
        <PackageId Condition="'$(Configuration)' == 'Release' And '$(Platform)' != 'AnyCPU'">$(RootNameSpace).$(Platform)</PackageId>
        <PackageId Condition="'$(Configuration)' == 'Release' And '$(Platform)' == 'AnyCPU'">$(RootNameSpace)</PackageId>
    </PropertyGroup>

    <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\..\RapidStreamer.png" Pack="true" Link="RapidStreamer.png" PackagePath="" />
        <None Include="..\..\..\README.md" Pack="true" Link="README.md" PackagePath="" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="NJsonSchema.Annotations" Version="11.2.0" />
        <PackageReference Include="RabbitMQ.Client" Version="7.1.2" />
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Debug'">
        <PackageReference Include="RapidStreamer.BuildingBlocks.Debug.ARM64" Version="1.0.109" Condition="'$(Platform)' == 'ARM64'" />
        <PackageReference Include="RapidStreamer.BuildingBlocks.Debug.x86" Version="1.0.109" Condition="'$(Platform)' == 'x86'" />
        <PackageReference Include="RapidStreamer.BuildingBlocks.Debug.x64" Version="1.0.109" Condition="'$(Platform)' == 'x64'" />
        <PackageReference Include="RapidStreamer.BuildingBlocks.Debug" Version="1.0.109" Condition="'$(Platform)' == 'AnyCPU'" />
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Release'">
        <PackageReference Include="RapidStreamer.BuildingBlocks.ARM64" Version="1.0.109" Condition="'$(Platform)' == 'ARM64'" />
        <PackageReference Include="RapidStreamer.BuildingBlocks.x86" Version="1.0.109" Condition="'$(Platform)' == 'x86'" />
        <PackageReference Include="RapidStreamer.BuildingBlocks.x64" Version="1.0.109" Condition="'$(Platform)' == 'x64'" />
        <PackageReference Include="RapidStreamer.BuildingBlocks" Version="1.0.109" Condition="'$(Platform)' == 'AnyCPU'" />
    </ItemGroup>

</Project>